CREATE DATABASE IF NOT EXISTS taskManager;
USE taskManager;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL
);


CREATE TABLE Notas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descrição TEXT
);

CREATE TABLE Blocos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    nota_id INT,
    FOREIGN KEY (nota_id) REFERENCES notas(id) ON DELETE SET NULL
);
